name: impact-visualizer
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas=1.0.5
  - xlrd=1.2.0
  - dash
  - scikit-learn=0.23.1
  - scipy=1.5.2
  - pip
  - pip:
    - plotly==4.9.0
    - dash_daq==0.5.0