# fonts
FONT_FAMILY = 'Avenir Next Condensed'
FONTSIZE_H1 = 48
FONTSIZE_H2 = 36
FONTSIZE_H3 = 24
FONTSIZE_H4 = 18
FONTSIZE_P = 16

# color scheme
BASE_LIGHT = '#ffffff'
BASE_DARK = '#0d0707'
PRIMARY = '#ff988f'
PRIMARY_LIGHT = '#ffb4ad'
PRIMARY_DARK = '#ff504a'

# window specs
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600

# page display
PAGE_PADX = 10
PAGE_PADY = 10

# header display
HEADER_PADX = 20
HEADER_PADY = 0
HEADER_MINSIZE = 150

# footer display
FOOTER_PADX = 5
FOOTER_PADY = 5
MAX_ROWS = 100

# buttons
BUTTON_BORDERWIDTH = 5

WIDGET_BUTTON_SPACING = 5
WIDGET_BUTTON_PADX = 3